version: '3'

services:
  redis:
    image: redis:5.0.8-alpine
    command: redis-server --appendonly yes
    expose:
      - 6379
    volumes:
      - redis-data:/data
    restart: always


  scrum-tools:
    build: .
    environment:
      REDIS_URI: "redis://redis:6379/0"
    links:
      - redis
    ports:
      - 3000:3000
    restart: always
    depends_on:
      - redis

volumes:
  redis-data:
