apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: scrum-tools-ingress
  annotations:
    # based on https://cert-manager.io/docs/tutorials/acme/ingress/
    cert-manager.io/issuer: "letsencrypt-prod"
spec:
  tls:
    - hosts:
        - scrumit.live
      secretName: scrum-tools-tls
  rules:
    - host: scrumit.live
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: scrum-tools
                port:
                  number: 3000
